import TypeEmbeddings
import TypeEmbeddings.Diagnostics.RevisedLimitations

/-! Consolidated main-result axiom audit. This is an explicit diagnostic target. -/

#print axioms TypeEmbeddings.rightMul_conjugate
#print axioms TypeEmbeddings.rightMul_adjoint_pairing
#print axioms TypeEmbeddings.rightMul_inner
#print axioms TypeEmbeddings.pureRGB_inner
#print axioms TypeEmbeddings.pureRGB_norm
#print axioms TypeEmbeddings.pureRGB_adjoint_pairing
#print axioms TypeEmbeddings.rightMulMatrix_apply
#print axioms TypeEmbeddings.rightMul_gram
#print axioms TypeEmbeddings.encoder_gram
#print axioms TypeEmbeddings.stacked_gram
#print axioms TypeEmbeddings.encoderMatrix_gram
#print axioms TypeEmbeddings.decoderMatrix_leftInverse
#print axioms TypeEmbeddings.decoder_fused
#print axioms TypeEmbeddings.decoder_roundTrip
#print axioms TypeEmbeddings.encoder_injective
#print axioms TypeEmbeddings.penrose_encoder
#print axioms TypeEmbeddings.penrose_decoder
#print axioms TypeEmbeddings.penrose_projection_symmetric
#print axioms TypeEmbeddings.penrose_inverse_symmetric
#print axioms TypeEmbeddings.reconstruction_score
#print axioms TypeEmbeddings.decoder_unique_leastSquares
#print axioms TypeEmbeddings.decoder_error_bound
#print axioms TypeEmbeddings.encoder_rank
#print axioms TypeEmbeddings.encoder_singularValue
#print axioms TypeEmbeddings.encoder_singularValue_tail
#print axioms TypeEmbeddings.encoder_condition
#print axioms TypeEmbeddings.encoder_opNorm
#print axioms TypeEmbeddings.decoder_opNorm
#print axioms TypeEmbeddings.channelValue_injective
#print axioms TypeEmbeddings.rgb_card
#print axioms TypeEmbeddings.channelValue_abs_gap
#print axioms TypeEmbeddings.rgbValue_injective
#print axioms TypeEmbeddings.nearestChannel_minimizes
#print axioms TypeEmbeddings.nearestChannel_tie
#print axioms TypeEmbeddings.nearestChannel_eq_round_clip
#print axioms TypeEmbeddings.nearestRGB_minimizes
#print axioms TypeEmbeddings.nearestRGB_global_minimizer
#print axioms TypeEmbeddings.decodeRGB_roundTrip
#print axioms TypeEmbeddings.decodeRGB_exact_of_margin
#print axioms TypeEmbeddings.decodeRGB_exact_of_noise
#print axioms TypeEmbeddings.channelNormalizer_pos
#print axioms TypeEmbeddings.channelProbability_sum
#print axioms TypeEmbeddings.rgbProbability_sum
#print axioms TypeEmbeddings.rgbProbability_mode
#print axioms TypeEmbeddings.rgbPMF
#print axioms TypeEmbeddings.rgbPMF_mode
#print axioms TypeEmbeddings.coreCoefficient_count
#print axioms TypeEmbeddings.untiedRGB_count
#print axioms TypeEmbeddings.untiedPadded_count
#print axioms TypeEmbeddings.scalePredictor_count
#print axioms TypeEmbeddings.atomicRGB_512_bf16_bytes
#print axioms TypeEmbeddings.encoder_cost
#print axioms TypeEmbeddings.decoder_cost
#print axioms TypeEmbeddings.roundTiesEven_interval
#print axioms TypeEmbeddings.roundTiesEven_halfway
#print axioms TypeEmbeddings.roundTiesEven_halfway_eq
#print axioms TypeEmbeddings.channel_minimizes_of_closed_interval
#print axioms TypeEmbeddings.nearestChannelEven_minimizes
#print axioms TypeEmbeddings.nearestChannelEven_exact_of_margin
#print axioms TypeEmbeddings.nearestRGBEven_minimizes
#print axioms TypeEmbeddings.nearestRGBEven_global_minimizer
#print axioms TypeEmbeddings.decodeRGBEven_roundTrip
#print axioms TypeEmbeddings.decodeRGBEven_exact_of_margin
#print axioms TypeEmbeddings.decodeRGBEven_exact_of_noise
#print axioms TypeEmbeddings.channelProbability_even_mode
#print axioms TypeEmbeddings.rgbProbability_even_mode
#print axioms TypeEmbeddings.normalizedBank_energy
#print axioms TypeEmbeddings.normalizedBank_pos
#print axioms TypeEmbeddings.residualDegrees_pos
#print axioms TypeEmbeddings.residualVariance_floor
#print axioms TypeEmbeddings.residualVariance_pos
#print axioms TypeEmbeddings.residualVariance_mono
#print axioms TypeEmbeddings.residualVariance_strict_mono
#print axioms TypeEmbeddings.residualVariance_eq_floor_iff
#print axioms TypeEmbeddings.residualVariance_at_code
#print axioms TypeEmbeddings.residualScale_sq
#print axioms TypeEmbeddings.softplusGain_pos
#print axioms TypeEmbeddings.softplusGain_one
#print axioms TypeEmbeddings.TypeCodebook.exists_separation
#print axioms TypeEmbeddings.nearestType_exact_of_margin
#print axioms TypeEmbeddings.typeProbability_sum
#print axioms TypeEmbeddings.type_logits_equal_norm
#print axioms TypeEmbeddings.typePMF
#print axioms TypeEmbeddings.typePMF_mode
#print axioms TypeEmbeddings.rgbReaderProbability_sum
#print axioms TypeEmbeddings.rgbReaderProbability_mode
#print axioms TypeEmbeddings.rgbReaderPMF
#print axioms TypeEmbeddings.typeReaderProbability_sum
#print axioms TypeEmbeddings.typeReaderProbability_mode
#print axioms TypeEmbeddings.typeReaderPMF
#print axioms TypeEmbeddings.rgbReaderSummary
#print axioms TypeEmbeddings.typeReaderSummary
#print axioms TypeEmbeddings.rgb_reconstruction_likelihood
#print axioms TypeEmbeddings.rgbReader_reconstruction_likelihood
#print axioms TypeEmbeddings.readerTemperature_pos
#print axioms TypeEmbeddings.rgbReader_reconstruction_temperature
#print axioms TypeEmbeddings.typedEmbedding_type_roundTrip
#print axioms TypeEmbeddings.typedEmbedding_value_roundTrip
#print axioms TypeEmbeddings.typedJoint_sum
#print axioms TypeEmbeddings.typedJoint_type_marginal
#print axioms TypeEmbeddings.typedJointPMF
#print axioms TypeEmbeddings.structuredCoefficient_count
#print axioms TypeEmbeddings.structured_512_count
#print axioms TypeEmbeddings.structured_output_work_bound
#print axioms TypeEmbeddings.structured_output_cost
#print axioms TypeEmbeddings.channelValue_bf16
#print axioms TypeEmbeddings.channelValue_dyadic
#print axioms TypeEmbeddings.wrongCode_zeroResidual
#print axioms TypeEmbeddings.sharedTwoInput_not_injective
#print axioms TypeEmbeddings.storageCounter_weights_bf16
#print axioms TypeEmbeddings.storageCounter_rounding
#print axioms TypeEmbeddings.storageCounter_decode_location
#print axioms TypeEmbeddings.storageCounter_wrong_decode
#print axioms TypeEmbeddings.wrongCode_floorWidth
#print axioms TypeEmbeddings.storageCounter_wrong_even_decode
