import TypeEmbeddings.Bank.Normalization
import TypeEmbeddings.Reader.Gain
import TypeEmbeddings.TypeCode.PMF
import TypeEmbeddings.Reader.Summary
import TypeEmbeddings.Probability.Reconstruction
import TypeEmbeddings.Typed.Interface
import TypeEmbeddings.Typed.Probability
import TypeEmbeddings.Counts.Structured
import TypeEmbeddings.Counts.StructuredCost

#print axioms TypeEmbeddings.normalizedBank_energy
#print axioms TypeEmbeddings.normalizedBank_pos
#print axioms TypeEmbeddings.residualDegrees_pos
#print axioms TypeEmbeddings.residualVariance_floor
#print axioms TypeEmbeddings.residualVariance_pos
#print axioms TypeEmbeddings.residualVariance_mono
#print axioms TypeEmbeddings.residualVariance_strict_mono
#print axioms TypeEmbeddings.residualVariance_eq_floor_iff
#print axioms TypeEmbeddings.residualVariance_at_code
#print axioms TypeEmbeddings.residualScale_sq
#print axioms TypeEmbeddings.softplusGain_pos
#print axioms TypeEmbeddings.softplusGain_one
#print axioms TypeEmbeddings.TypeCodebook.exists_separation
#print axioms TypeEmbeddings.nearestType_exact_of_margin
#print axioms TypeEmbeddings.typeProbability_sum
#print axioms TypeEmbeddings.type_logits_equal_norm
#print axioms TypeEmbeddings.typePMF
#print axioms TypeEmbeddings.typePMF_mode
#print axioms TypeEmbeddings.rgbReaderProbability_sum
#print axioms TypeEmbeddings.rgbReaderProbability_mode
#print axioms TypeEmbeddings.rgbReaderPMF
#print axioms TypeEmbeddings.typeReaderProbability_sum
#print axioms TypeEmbeddings.typeReaderProbability_mode
#print axioms TypeEmbeddings.typeReaderPMF
#print axioms TypeEmbeddings.rgbReaderSummary
#print axioms TypeEmbeddings.typeReaderSummary
#print axioms TypeEmbeddings.rgb_reconstruction_likelihood
#print axioms TypeEmbeddings.rgbReader_reconstruction_likelihood
#print axioms TypeEmbeddings.typedEmbedding_type_roundTrip
#print axioms TypeEmbeddings.typedEmbedding_value_roundTrip
#print axioms TypeEmbeddings.typedJoint_sum
#print axioms TypeEmbeddings.typedJoint_type_marginal
#print axioms TypeEmbeddings.typedJointPMF
#print axioms TypeEmbeddings.structuredCoefficient_count
#print axioms TypeEmbeddings.structured_512_count
#print axioms TypeEmbeddings.structured_output_work_bound
#print axioms TypeEmbeddings.structured_output_cost
