import QNN
import Examples.Autoencoder

/-! Reproducible axiom audit of the current main definitions and results. -/
#print axioms QNN.hamilton_rules
#print axioms QNN.multiplication_not_commutative
#print axioms QNN.conjugate_mul
#print axioms QNN.norm_sq_components
#print axioms QNN.norm_components
#print axioms QNN.mul_conjugate
#print axioms QNN.pureEuclidean
#print axioms QNN.pure_mul
#print axioms QNN.unitConjugation
#print axioms QNN.unit_conjugate_cross
#print axioms QNN.unit_conjugate_oriented_volume
#print axioms QNN.axisAngle_unit
#print axioms QNN.rodrigues
#print axioms QNN.rodrigues_orthogonal
#print axioms QNN.weightAction_norm
#print axioms QNN.activation_range
#print axioms QNN.loss_components
#print axioms QNN.loss_eq_zero
#print axioms QNN.weightAction_hasFDerivAt
#print axioms QNN.weightDerivative_apply
#print axioms QNN.activation_hasFDerivAt
#print axioms QNN.loss_hasGradientAt
#print axioms QNN.gradient_chain
#print axioms QNN.quaternion_update_eq_partials
#print axioms QNN.Network.input_hasFDerivAt
#print axioms QNN.Network.input_gradient_chain
#print axioms QNN.Network.pullback_eq
#print axioms QNN.Network.pullback_hasFDerivAt
#print axioms QNN.neuron_eq_connection
#print axioms QNN.connection_loss_gradient
#print axioms QNN.connection_backprop
#print axioms QNN.connection_update_components
#print axioms QNN.componentPartial_hasDerivAt
#print axioms QNN.neuron_update_eq_connection
#print axioms QNN.Layer.weight_hasFDerivAt
#print axioms QNN.Layer.euclideanWeight_hasFDerivAt
#print axioms QNN.Network.WeightIndex.replace_self
#print axioms QNN.Network.WeightIndex.hasFDerivAt
#print axioms QNN.Network.WeightIndex.backprop_eq
#print axioms QNN.Network.WeightIndex.backprop_hasGradientAt
#print axioms QNN.Network.WeightIndex.update_components
#print axioms QNN.signalLoss_eq_outputLoss
#print axioms QNN.signalLoss_hasGradientAt
#print axioms QNN.Network.weightGradient_hasGradientAt
#print axioms QNN.Network.weightGradient_component
#print axioms QNN.Network.WeightIndex.reindex_value
#print axioms QNN.Network.trainStep
#print axioms QNN.Network.trainStep_components
#print axioms QNN.weightAction_parametric_differentiableAt
#print axioms QNN.neuron_parametric_differentiableAt
#print axioms QNN.Network.mapWeights_parametric_differentiableAt
#print axioms QNN.Network.objective_parametric_differentiableAt
#print axioms QNN.Examples.hidden_update
